services:
  api-tcc:
    build: .
    container_name: nestjs_container
    env_file: .env
    restart: always
    ports:
      - '3000:3000'
    dns:
      - 8.8.8.8
      - 8.8.4.4
      - 1.1.1.1
volumes:
  pgdata:
