version: '3.8'

services:
  db-tcc:
    image: postgres:15-alpine
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rafael
      POSTGRES_DB: tcc_database
    ports:
      - '5433:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  api-tcc:
    build: .
    container_name: nestjs_container
    env_file: .env
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - db-tcc
    dns:
      - 8.8.8.8
      - 8.8.4.4
    environment:
      DB_HOST: db-tcc
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: rafael
      DB_NAME: tcc_database

volumes:
  pgdata:
